# Generated by Django 4.1.3 on 2022-12-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_cnic', models.CharField(db_index=True, max_length=13, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_age', models.IntegerField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=13)),
                ('client_details', models.TextField()),
                ('client_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_cnic', models.CharField(db_index=True, max_length=13, primary_key=True, serialize=False, unique=True)),
                ('lawyer_name', models.CharField(max_length=100)),
                ('lawyer_age', models.IntegerField()),
                ('lawyer_email', models.EmailField(max_length=254)),
                ('lawyer_phone', models.CharField(max_length=13)),
                ('lawyer_qualification', models.CharField(default='LLB', max_length=100)),
                ('lawyer_specialization', models.CharField(max_length=200)),
                ('lawyer_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_reference_no', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('case_creation_date', models.DateTimeField()),
                ('case_status', models.CharField(choices=[('OP', 'Open'), ('AC', 'Accepted'), ('CL', 'Closed'), ('RE', 'Rejected')], default='OP', max_length=2)),
                ('case_details', models.TextField()),
                ('case_type', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='mainApp.client')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.lawyer')),
            ],
        ),
    ]
